add greek translation
Jezzamonn/fourier pull request #59
Opened 2023-02-26 11:25 UTC by antgr

2023-03-18 00:56 UTC, Jezzamonn requested changes
Thanks so much for adding the translation! Here's a few extra words that need to be translated, that are kind of hidden within the HTML part of the article. I've left comments in GitHub for those.

There are some other pieces of information I'll need translated to get this on the site:

- A translation of the title: "An Interactive Introduction to Fourier Transforms"
- Translator credits for you: "Translated by ___"
- Optionally, if you would like your name to link to your personal website, give me the link and I can add that! An example is in the Spanish translation of the site: https://www.jezzamon.com/fourier/es.html

2023-03-18 00:56 UTC, Jezzamonn commented on CNAME
What's the purpose of this file?

2023-03-18 00:56 UTC, Jezzamonn commented on content/content-gr.md
> +<button id="together-button" class="button">Play Full Wave</button>
"Play Full Wave" needs to be translated

2023-03-18 00:56 UTC, Jezzamonn commented on content/content-gr.md
> +<button id="split-button-1" class="button">Play High Frequency</button>
"Play High Frequency" needs to be translated

2023-03-18 00:56 UTC, Jezzamonn commented on content/content-gr.md
> +<button id="split-button-2" class="button">Play Low Frequency</button>
"Play Low Frequency" needs to be translated

2023-03-18 00:56 UTC, Jezzamonn commented on content/content-gr.md
> +<button id="square-wave-button" class="button">Play Wave</button>
"Play Wave" needs to be translated

2023-03-18 00:56 UTC, Jezzamonn commented on content/content-gr.md
> +    <p id="wave-draw-instruction" class="instruction wave-instruction">Draw here!</p>
"Draw here!" needs to be translated

2023-03-18 00:56 UTC, Jezzamonn commented on content/content-gr.md
> +<button id="wave-draw-button" class="button">Play Wave</button>
"Play Wave" needs to be translated

2023-03-18 00:56 UTC, Jezzamonn commented on content/content-gr.md
> +    <p id="draw-zone-instruction" class="instruction">Draw here!</p>
"Draw here!" needs to be translated

2023-03-18 00:56 UTC, Jezzamonn commented on content/content-gr.md
> +    <button id="draw-zone-undo-button" class="button embedded-button">Undo</button>
"Undo" needs to be translated

2023-04-12 15:45 UTC, Jezzamonn commented
Would love to get this on the site! If you want I can have a go at translating those words for you?

2024-01-17 10:52 UTC, Jezzamonn commented
Hi! Just following up on this -- there are a few extra sections that need to be translated before I can get this on the site. Would love to get this added.

2025-05-17 02:42 UTC, TsekrekosEA commented
Hello! Does this Greek translation still require those amendments? I'd love to either finish this translation or if needed remake it. Should I open my own PR?

2026-01-05 19:16 UTC, closed without merging